Repository uxlfoundation/oneDPL, pull requests merged in 2024-12, with the labels that each got.

#1940 Defining developer roles, responsibilities, and privileges and leadership process
  CONTRIBUTING.md
  MAINTAINERS.md
Labels: RFC

#1867 Adding note about potential issue with ranges::iter_swap customizations.
  documentation/library_guide/parallel_api/parallel_range_algorithms.rst
Labels: documentation

#1949 [Cmake] Make SYCL detection more portable
  CMakeLists.txt
Labels: enhancement

#1571 [onedpl][ranges][test] Added std ranges to oneDPL Tested API
  test/CMakeLists.txt
  test/xpu_api/ranges/xpu_std_all_view.pass.cpp
  test/xpu_api/ranges/xpu_std_drop_view.pass.cpp
  test/xpu_api/ranges/xpu_std_iota_view.pass.cpp
  test/xpu_api/ranges/xpu_std_ranges_test.h
  test/xpu_api/ranges/xpu_std_reverse_view.pass.cpp
  test/xpu_api/ranges/xpu_std_single_view.pass.cpp
  test/xpu_api/ranges/xpu_std_subrange.pass.cpp
  test/xpu_api/ranges/xpu_std_take_view.pass.cpp
  test/xpu_api/ranges/xpu_std_transform_view.pass.cpp
Labels: ready for test, test

#1971 RFC process clarification
  rfcs/README.md
  rfcs/experimental/README.md
  rfcs/proposed/README.md
  rfcs/supported/README.md
  rfcs/template.md
Labels: RFC

#1970 Optimization of `__serial_merge` function
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
Labels: enhancement

#1933 Optimize `merge` algorithm for largest data sizes
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
  test/parallel_api/algorithm/alg.merge/merge.pass.cpp
Labels: enhancement

#1954 Fall back to SYCL 2020 API for a generic SYCL implementation
  include/oneapi/dpl/internal/scan_by_segment_impl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_by_segment.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
  include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
  include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
  include/oneapi/dpl/pstl/utils.h
  test/general/test_policies.pass.cpp
Labels: bug, enhancement
