Repository uxlfoundation/oneDPL, pull requests merged in 2024-10, with the labels that each got.

#1878 Add the directory structure for RFC documents
  rfcs/README.md
  rfcs/archived/README.md
  rfcs/experimental/README.md
  rfcs/proposed/README.md
  rfcs/supported/README.md
  rfcs/template.md
Labels: RFC

#1883 Include a missing header
  include/oneapi/dpl/pstl/utils_ranges.h
Labels: bug

#1884 Fix includes in scan_2 test
  test/parallel_api/numeric/numeric.ops/scan_2.pass.cpp
Labels: bug, test

#1887 Move difference_t utility to utils_ranges header
  include/oneapi/dpl/pstl/execution_defs.h
  include/oneapi/dpl/pstl/glue_algorithm_ranges_defs.h
  include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
  include/oneapi/dpl/pstl/glue_numeric_ranges_defs.h
  include/oneapi/dpl/pstl/glue_numeric_ranges_impl.h
  include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
  include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h
  include/oneapi/dpl/pstl/utils_ranges.h
Labels: enhancement

#1894 Fix inclusion order of numeric header
  include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h
Labels: bug

#1896 Include all necessary standard headers in utils_ranges.h
  include/oneapi/dpl/pstl/utils_ranges.h
Labels: bug

#1872 Reduce the number of kernels to compile in merge-sort
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
Labels: enhancement

#1918 Fix test_policies for FPGA
  test/general/test_policies.pass.cpp
Labels: test

#1927 Make kernel names unique in radix sort
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
Labels: bug
