Repository uxlfoundation/oneDPL, pull requests merged in 2025-09, with the labels that each got.

#2427 Align size types for set alg helpers
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
Labels: bug

#2456 Update compiler version in tests
  test/support/test_config.h
Labels: test

#2455 Fix incorrect usage of `_DifferenceType1` / `_DifferenceType2` in the code
  include/oneapi/dpl/pstl/algorithm_impl.h
  include/oneapi/dpl/pstl/algorithm_ranges_impl.h
Labels: bug

#2460 Fix coverity issues in set parallel range algorithms #1
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
  include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
Labels: bug

#2458 Fix header inclusion memory tests for libstdc++10
  test/general/header_inclusion_order_memory_0.pass.cpp
  test/general/header_inclusion_order_memory_1.pass.cpp
Labels: test

#2464 Skip XPU drop_view test with libstdc++10
  test/support/test_config.h
  test/xpu_api/ranges/xpu_std_drop_view.pass.cpp
Labels: test

#2465 Histogram: workaround kernel compilation issues with icpx 2025.3
  documentation/release_notes.rst
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
Labels: bug

#2344 Update a known issue for range-based count_if
  documentation/release_notes.rst
Labels: documentation

#2384 Using existing functional objects instead lambdas in template code
  include/oneapi/dpl/pstl/algorithm_ranges_impl.h
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
Labels: enhancement

#2478 Remove `__predicate` and `__compare` structs
  include/oneapi/dpl/pstl/algorithm_ranges_impl.h
  include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
  include/oneapi/dpl/pstl/utils.h
Labels: enhancement

#2475 Fix range iterators usage after range perfect forwarding
  include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/memory_ranges_impl_hetero.h
Labels: bug, enhancement

#2481 Ranges stuff refactoring
  include/oneapi/dpl/pstl/algorithm_ranges_impl.h
  include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
  include/oneapi/dpl/pstl/memory_ranges_impl.h
Labels: enhancement

#2388 Replace `typedef` to `using` in oneDPL code and tests
  include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h
  include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h
  include/oneapi/dpl/internal/random_impl/random_common.h
  include/oneapi/dpl/internal/reduce_by_segment_impl.h
  include/oneapi/dpl/pstl/algorithm_impl.h
  include/oneapi/dpl/pstl/experimental/internal/for_loop.h
  include/oneapi/dpl/pstl/glue_algorithm_impl.h
  include/oneapi/dpl/pstl/glue_memory_impl.h
  include/oneapi/dpl/pstl/glue_numeric_impl.h
  include/oneapi/dpl/pstl/iterator_impl.h
  include/oneapi/dpl/pstl/numeric_impl.h
  include/oneapi/dpl/pstl/parallel_backend_tbb.h
  include/oneapi/dpl/pstl/parallel_backend_utils.h
  include/oneapi/dpl/pstl/parallel_impl.h
  include/oneapi/dpl/pstl/unseq_backend_simd.h
  include/oneapi/dpl/pstl/utils.h
  test/general/sycl_iterator/sycl_iterator_find.pass.cpp
  test/general/sycl_iterator/sycl_iterator_for.pass.cpp
  test/general/sycl_iterator/sycl_iterator_reduce.pass.cpp
  test/general/sycl_iterator/sycl_iterator_scan.pass.cpp
  test/general/sycl_iterator/sycl_iterator_sort.pass.cpp
  test/parallel_api/algorithm/alg.merge/merge.pass.cpp
  test/parallel_api/algorithm/alg.nonmodifying/for_each.pass.cpp
  test/parallel_api/algorithm/alg.nonmodifying/mismatch.pass.cpp
  test/parallel_api/algorithm/alg.sorting/alg.binary.search/binary.search/binary_search.pass.cpp
  test/parallel_api/algorithm/alg.sorting/alg.binary.search/lower.bound/lower_bound.pass.cpp
  test/parallel_api/algorithm/alg.sorting/alg.binary.search/upper.bound/upper_bound.pass.cpp
  test/parallel_api/algorithm/alg.sorting/alg.min.max/minmax_element.pass.cpp
  test/parallel_api/algorithm/alg.sorting/is_sorted.pass.cpp
  test/parallel_api/iterator/zip_iterator_find.pass.cpp
  test/parallel_api/iterator/zip_iterator_for.pass.cpp
  test/parallel_api/iterator/zip_iterator_merge.pass.cpp
  test/parallel_api/iterator/zip_iterator_reduce.pass.cpp
  test/parallel_api/iterator/zip_iterator_scan.pass.cpp
  test/parallel_api/memory/specialized.algorithms/uninitialized_construct.pass.cpp
  test/parallel_api/memory/specialized.algorithms/uninitialized_copy_move.pass.cpp
  test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp
  test/parallel_api/numeric/numeric.ops/inclusive_scan_by_segment.pass.cpp
  test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp
  test/support/counting_predicates.h
  test/support/iterator_utils.h
  test/support/scan_serial_impl.h
  test/support/test_iterators.h
  test/support/utils.h
  test/support/utils_sequence.h
Labels: enhancement
