Repository uxlfoundation/oneDPL, pull requests merged in 2025-04, with the labels that each got.

#2157 Comment/remove unused parameter `_ExecutionPolicy&& __exec` in some functions
  include/oneapi/dpl/pstl/algorithm_impl.h
  include/oneapi/dpl/pstl/numeric_impl.h
  include/oneapi/dpl/pstl/omp/parallel_scan.h
  include/oneapi/dpl/pstl/parallel_backend_serial.h
  include/oneapi/dpl/pstl/parallel_backend_tbb.h
Labels: enhancement

#2168 Avoid some `auto` return types
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_for.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
Labels: enhancement

#2152 Removal `ExecutionPolicy` template parameter from sycl utilities
  include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_dispatchers.h
  include/oneapi/dpl/internal/scan_by_segment_impl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_for.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_by_segment.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
Labels: enhancement

#2178 Fix philox_test.pass
  test/xpu_api/random/conformance_tests/philox_test.pass.cpp
Labels: test

#2148 Removal `ExecutionPolicy` template parameter from `brick`s
  include/oneapi/dpl/internal/async_impl/async_impl_hetero.h
  include/oneapi/dpl/internal/async_impl/glue_async_impl.h
  include/oneapi/dpl/pstl/algorithm_fwd.h
  include/oneapi/dpl/pstl/algorithm_impl.h
  include/oneapi/dpl/pstl/algorithm_ranges_impl.h
  include/oneapi/dpl/pstl/glue_algorithm_impl.h
  include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
  include/oneapi/dpl/pstl/glue_memory_impl.h
  include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
  include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
  include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/histogram_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h
  test/general/implementation_details/device_copyable.pass.cpp
Labels: enhancement

#2181 Update compiler version in tests
  test/support/test_config.h
Labels: test

#2167 Define the amount of results in `__result_and_scratch_storage` in compile-time
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
Labels: enhancement

#2185 Fix predicate in `test_adjacent_difference`
  test/general/sycl_iterator/sycl_iterator_for.pass.cpp
Labels: bug, test

#2153 Replacement of internal `lambda` in `oneDPL` code by functional objects
  include/oneapi/dpl/internal/binary_search_impl.h
  include/oneapi/dpl/pstl/glue_algorithm_impl.h
  include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
  include/oneapi/dpl/pstl/glue_memory_impl.h
  include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
  include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h
  include/oneapi/dpl/pstl/utils.h
Labels: enhancement

#2189 Fix incorrect return type in the `__pattern_swap` function for `__hetero_tag` + ranges
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
Labels: bug

#2193 Fix double type definition in `__parallel_transform_reduce_work_group_kernel_submitter::operator()`
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
Labels: bug

#2161 Removal `ExecutionPolicy` from submitters and etc. stuff
  include/oneapi/dpl/experimental/kt/esimd_radix_sort.h
  include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_dispatchers.h
  include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_submitters.h
  include/oneapi/dpl/experimental/kt/single_pass_scan.h
  include/oneapi/dpl/internal/async_impl/async_impl_hetero.h
  include/oneapi/dpl/internal/async_impl/glue_async_impl.h
  include/oneapi/dpl/internal/scan_by_segment_impl.h
  include/oneapi/dpl/pstl/glue_algorithm_impl.h
  include/oneapi/dpl/pstl/glue_memory_impl.h
  include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_for.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_by_segment.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
  include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
  include/oneapi/dpl/pstl/hetero/histogram_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h
Labels: enhancement

#2197 Revert: Removal ExecutionPolicy from submitters and etc. stuff #2161
  include/oneapi/dpl/experimental/kt/esimd_radix_sort.h
  include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_dispatchers.h
  include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_submitters.h
  include/oneapi/dpl/experimental/kt/single_pass_scan.h
  include/oneapi/dpl/internal/async_impl/async_impl_hetero.h
  include/oneapi/dpl/internal/async_impl/glue_async_impl.h
  include/oneapi/dpl/internal/scan_by_segment_impl.h
  include/oneapi/dpl/pstl/glue_algorithm_impl.h
  include/oneapi/dpl/pstl/glue_memory_impl.h
  include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_for.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_by_segment.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
  include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
  include/oneapi/dpl/pstl/hetero/histogram_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h
Labels: enhancement

#2200 Remove some duplicated structures
  include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
  include/oneapi/dpl/pstl/hetero/utils_hetero.h
Labels: bug

#2194 Fix an error in __one_group_submitter
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
Labels: bug

#2198 Removal `ExecutionPolicy` from submitters and etc. stuff (attemp #2)
  include/oneapi/dpl/internal/scan_by_segment_impl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_for.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_by_segment.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
Labels: enhancement

#2213 Fix segmented scans: remove extra template parameter
  include/oneapi/dpl/internal/scan_by_segment_impl.h
Labels: bug
