Repository uxlfoundation/oneDPL, pull requests merged in 2025-01, with the labels that each got.

#1987 Bugfix for reduce-by-segment with differing input and output types
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  test/parallel_api/numeric/numeric.ops/reduce_by_segment_zip.pass.cpp
Labels: bug

#1979 Do not use deprecated sub-group load/store extension
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
Labels: bug

#1990 Fix ambiguous call to sycl::min
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
Labels: bug

#1916 RFC to design a unified oneDPL approach to asynchrony
  rfcs/archived/asynchronous_api_general/readme.md
Labels: RFC

#1935 Remove usage of `__kernel_name_generator` as not required for non-compiled Kernel's
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
Labels: bug, enhancement

#2000 Update broken macro for XPU tests
  test/support/test_config.h
Labels: test

#2002 Ensure `__max_sg_size` is at least 4 in sort
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
Labels: bug

#2008 Modernize Tested API example, replace cl_int
  documentation/library_guide/api_for_sycl_kernels/tested_standard_cpp_api.rst
  test/xpu_api/language.support/support.types/nullptr_t.pass.cpp
Labels: documentation, test

#1930 RFC for histogram CPU implementation
  rfcs/proposed/algorithms_histogram_cpu_backends/README.md
Labels: RFC

#1991 Make kernel compilation logic more portable
  include/oneapi/dpl/internal/scan_by_segment_impl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_by_segment.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
  include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
  include/oneapi/dpl/pstl/onedpl_config.h
Labels: enhancement

#2013 Fix compile error in `__serial_merge`
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
Labels: bug

#2004 Bugfix for device copyable of unique copy helper
  include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
  test/general/implementation_details/device_copyable.pass.cpp
Labels: bug

#2022 Fix performance issue in `__serial_merge`
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
Labels: enhancement

#1977 Optimize `merge_sort` algorithm for largest data sizes
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
  test/parallel_api/algorithm/alg.merge/merge.pass.cpp
  test/parallel_api/algorithm/alg.sorting/sort.pass.cpp
Labels: enhancement

#1976 Re-implement SYCL backend `parallel_for` to improve bandwidth utilization
  include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_submitters.h
  include/oneapi/dpl/internal/async_impl/async_impl_hetero.h
  include/oneapi/dpl/internal/binary_search_impl.h
  include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_for.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
  include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
  include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
  include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
  include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
  include/oneapi/dpl/pstl/hetero/histogram_impl_hetero.h
  include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h
  include/oneapi/dpl/pstl/utils.h
  test/general/implementation_details/device_copyable.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/alg.reverse/reverse.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/alg.reverse/reverse_copy.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/copy_move.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/generate.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/replace.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/replace_copy.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/rotate.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/rotate_copy.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/shift_left_right.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/swap_ranges.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/transform_binary.pass.cpp
  test/parallel_api/algorithm/alg.modifying.operations/transform_unary.pass.cpp
  test/parallel_api/algorithm/alg.nonmodifying/for_each.pass.cpp
  test/parallel_api/algorithm/alg.nonmodifying/transform_if.pass.cpp
  test/parallel_api/numeric/numeric.ops/adjacent_difference.pass.cpp
  test/support/utils.h
Labels: enhancement
