Repository uxlfoundation/oneDPL, pull requests merged in 2025-08, with the labels that each got.

#2370 Remove extra declarations from sort tests
  test/parallel_api/algorithm/alg.sorting/sort_by_key_common.h
Labels: test

#2269 [oneDPL][rfc][ranges][L1] the third portion of the range based API
  rfcs/proposed/range_algorithms_3/README.md
Labels: RFC

#2371 Fix compile error in `inclusive_scan` and `exclusive_scan` over reverse iterators with different source iterator types
  include/oneapi/dpl/pstl/utils.h
  test/general/implementation_details/test_sycl_iterator_operations.pass.cpp
  test/general/sycl_iterator/sycl_iterator_operations.pass.cpp
  test/parallel_api/numeric/numeric.ops/exclusive_scan.pass.cpp
  test/support/sycl_alloc_utils.h
  test/support/test_config.h
Labels: bug

#2386 Fix temporary buffer data type in `__pattern_set_union` and `__pattern_set_symmetric_difference` for `__hetero_tag`
  include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
Labels: bug

#2395 Fix return types in `oneapi::dpl::__internal::__ranges::__pattern_minmax_element` and `oneapi::dpl::__internal::__ranges::__pattern_mismatch`
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
Labels: bug

#2402 Fix `oneapi::dpl::__internal::__compare` specializations
  include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
Labels: bug

#2401 Replace `std::exclusive_scan` to `exclusive_scan_serial` call
  test/parallel_api/numeric/numeric.ops/exclusive_scan.pass.cpp
Labels: test

#2355 Move only type support for [transform_]reduce for host backends
  documentation/library_guide/introduction.rst
  include/oneapi/dpl/internal/async_impl/glue_async_impl.h
  include/oneapi/dpl/internal/serial_numeric_impl.h
  include/oneapi/dpl/pstl/glue_numeric_impl.h
  include/oneapi/dpl/pstl/glue_numeric_ranges_impl.h
  include/oneapi/dpl/pstl/numeric_impl.h
  include/oneapi/dpl/pstl/omp/parallel_transform_reduce.h
  include/oneapi/dpl/pstl/parallel_backend_serial.h
  include/oneapi/dpl/pstl/parallel_backend_tbb.h
  include/oneapi/dpl/pstl/unseq_backend_simd.h
  include/oneapi/dpl/pstl/utils.h
  test/parallel_api/numeric/numeric.ops/reduce.pass.cpp
  test/parallel_api/numeric/numeric.ops/transform_reduce.pass.cpp
  test/support/utils.h
Labels: bug
